import { CartProvider } from './cart/context/CartContext';
import './globals.css';


export const metadata = {
  title: 'Loja STG',
  description: 'Generated by Next.js',
}



export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}